service: cloudevents-demo

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    -  Effect: 'Allow'
       Action:
         - 'rekognition:*'
       Resource: '*'

functions:

  # Publisher: Converts native AWS S3 event to a AWS S3 CloudEvent
  publisher:
    handler: publisher.publisher
    events:
      - s3:
          bucket: cloudevents
          event: s3:ObjectCreated:*

  # PublisherTest: Converts native AWS S3 event to a AWS S3 CloudEvent
  publisherTester:
    handler: publisher.publisherTest
    events:
      - schedule: rate(2 minutes)

  # Subscriber: Subscribes to AWS S3 CloudEvents & processes images
  imageSubscriber:
    handler: subscribers.image
    events:
      - http:
          path: imageSubscriber
          method: post
          cors: true
