service: cloudevents-demo

provider:
  name: aws
  runtime: nodejs6.10

functions:

  # Publisher: Converts native AWS S3 event to a CloudEvent
  publisher:
    handler: publisher.publisher
    events:
      - s3:
          bucket: cloudevents
          event: s3:ObjectCreated:*

  # Subscriber: Subscribes to CloudEvent & processes JSON
  reviewSubscriber:
    handler: subscribers.review
    events:
      - http:
          path: reviewSubscriber
          method: post
          cors: true

  # Subscriber: Subscribes to CloudEvents & processes images
  imageSubscriber:
    handler: subscribers.image
    events:
      - http:
          path: imageSubscriber
          method: post
          cors: true
