service: cloudevents-demo

provider:
  name: aws
  runtime: nodejs6.10

functions:
  reviewPublisher:
    handler: handler.reviewPublisher
    events:
      - s3:
          bucket: cloudevents
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json
  reviewSubscriber:
    handler: handler.reviewSubscriber
    events:
      - http:
          path: reviewSubscriber
          method: post
          cors: true
